# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: ip/ram0/ram0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ram0 || ORIG_REF_NAME==ram0} -quiet] -quiet

# Block Designs: bd/design_1/design_1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_cg_fpga_0_0/design_1_cg_fpga_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_cg_fpga_0_0 || ORIG_REF_NAME==design_1_cg_fpga_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_bus_to_group_0_0/design_1_bus_to_group_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_bus_to_group_0_0 || ORIG_REF_NAME==design_1_bus_to_group_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_bus_to_group_1_0/design_1_bus_to_group_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_bus_to_group_1_0 || ORIG_REF_NAME==design_1_bus_to_group_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_single_4_to_bus_2_0/design_1_single_4_to_bus_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_single_4_to_bus_2_0 || ORIG_REF_NAME==design_1_single_4_to_bus_2_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_alu_74181_3_0/design_1_alu_74181_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_alu_74181_3_0 || ORIG_REF_NAME==design_1_alu_74181_3_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_alu_74181_2_0/design_1_alu_74181_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_alu_74181_2_0 || ORIG_REF_NAME==design_1_alu_74181_2_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_alu_74181_1_0/design_1_alu_74181_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_alu_74181_1_0 || ORIG_REF_NAME==design_1_alu_74181_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_alu_74181_0_0/design_1_alu_74181_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_alu_74181_0_0 || ORIG_REF_NAME==design_1_alu_74181_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_single_4_to_bus_0_0/design_1_single_4_to_bus_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_single_4_to_bus_0_0 || ORIG_REF_NAME==design_1_single_4_to_bus_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_single_4_to_bus_1_0/design_1_single_4_to_bus_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_single_4_to_bus_1_0 || ORIG_REF_NAME==design_1_single_4_to_bus_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_group_to_bus_0_0/design_1_group_to_bus_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_group_to_bus_0_0 || ORIG_REF_NAME==design_1_group_to_bus_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_carry_lookahead_74182_0_0/design_1_carry_lookahead_74182_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_carry_lookahead_74182_0_0 || ORIG_REF_NAME==design_1_carry_lookahead_74182_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_bus_to_single_3_0_0/design_1_bus_to_single_3_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_bus_to_single_3_0_0 || ORIG_REF_NAME==design_1_bus_to_single_3_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconstant_0_0/design_1_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xlconstant_0_0 || ORIG_REF_NAME==design_1_xlconstant_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconstant_1_0/design_1_xlconstant_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xlconstant_1_0 || ORIG_REF_NAME==design_1_xlconstant_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and_gate_0_11/design_1_and_gate_0_11.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and_gate_0_11 || ORIG_REF_NAME==design_1_and_gate_0_11} -quiet] -quiet

# IP: bd/design_1/ip/design_1_group_to_bus_8_0_0_0/design_1_group_to_bus_8_0_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_group_to_bus_8_0_0_0 || ORIG_REF_NAME==design_1_group_to_bus_8_0_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ic_74161_0_1/design_1_ic_74161_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_ic_74161_0_1 || ORIG_REF_NAME==design_1_ic_74161_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ic_74161_1_1/design_1_ic_74161_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_ic_74161_1_1 || ORIG_REF_NAME==design_1_ic_74161_1_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_register_16bit_0_0/design_1_register_16bit_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_register_16bit_0_0 || ORIG_REF_NAME==design_1_register_16bit_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_trans_0_1/design_1_trans_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_trans_0_1 || ORIG_REF_NAME==design_1_trans_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_pc_0_0/design_1_pc_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_pc_0_0 || ORIG_REF_NAME==design_1_pc_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_register_16bit_0_1/design_1_register_16bit_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_register_16bit_0_1 || ORIG_REF_NAME==design_1_register_16bit_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_bus_mux_16_0_0/design_1_bus_mux_16_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_bus_mux_16_0_0 || ORIG_REF_NAME==design_1_bus_mux_16_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_register_16bit_1_0/design_1_register_16bit_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_register_16bit_1_0 || ORIG_REF_NAME==design_1_register_16bit_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_register_16bit_2_0/design_1_register_16bit_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_register_16bit_2_0 || ORIG_REF_NAME==design_1_register_16bit_2_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_register_16bit_3_0/design_1_register_16bit_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_register_16bit_3_0 || ORIG_REF_NAME==design_1_register_16bit_3_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_register_16bit_4_0/design_1_register_16bit_4_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_register_16bit_4_0 || ORIG_REF_NAME==design_1_register_16bit_4_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_register_16bit_5_0/design_1_register_16bit_5_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_register_16bit_5_0 || ORIG_REF_NAME==design_1_register_16bit_5_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_register_16bit_6_0/design_1_register_16bit_6_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_register_16bit_6_0 || ORIG_REF_NAME==design_1_register_16bit_6_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_register_16bit_7_0/design_1_register_16bit_7_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_register_16bit_7_0 || ORIG_REF_NAME==design_1_register_16bit_7_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_register_16bit_8_0/design_1_register_16bit_8_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_register_16bit_8_0 || ORIG_REF_NAME==design_1_register_16bit_8_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_group_to_bus_12_0_0_0/design_1_group_to_bus_12_0_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_group_to_bus_12_0_0_0 || ORIG_REF_NAME==design_1_group_to_bus_12_0_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_group_to_bus_12_10_0_0_0/design_1_group_to_bus_12_10_0_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_group_to_bus_12_10_0_0_0 || ORIG_REF_NAME==design_1_group_to_bus_12_10_0_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_single_4_to_bus_1_1/design_1_single_4_to_bus_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_single_4_to_bus_1_1 || ORIG_REF_NAME==design_1_single_4_to_bus_1_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_single_4_to_bus_2_1/design_1_single_4_to_bus_2_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_single_4_to_bus_2_1 || ORIG_REF_NAME==design_1_single_4_to_bus_2_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_upc_0_0/design_1_upc_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_upc_0_0 || ORIG_REF_NAME==design_1_upc_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ic_74161_0_0/design_1_ic_74161_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_ic_74161_0_0 || ORIG_REF_NAME==design_1_ic_74161_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ic_74161_1_0/design_1_ic_74161_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_ic_74161_1_0 || ORIG_REF_NAME==design_1_ic_74161_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ic_74161_2_0/design_1_ic_74161_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_ic_74161_2_0 || ORIG_REF_NAME==design_1_ic_74161_2_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_bus_to_group_12_0_0_0/design_1_bus_to_group_12_0_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_bus_to_group_12_0_0_0 || ORIG_REF_NAME==design_1_bus_to_group_12_0_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_bus_to_single_4_0_1/design_1_bus_to_single_4_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_bus_to_single_4_0_1 || ORIG_REF_NAME==design_1_bus_to_single_4_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_decoder_2to4_0_1/design_1_decoder_2to4_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_decoder_2to4_0_1 || ORIG_REF_NAME==design_1_decoder_2to4_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_single_2_to_bus_0_1/design_1_single_2_to_bus_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_single_2_to_bus_0_1 || ORIG_REF_NAME==design_1_single_2_to_bus_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_bus_to_single_8_0_0/design_1_bus_to_single_8_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_bus_to_single_8_0_0 || ORIG_REF_NAME==design_1_bus_to_single_8_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_decoder_3to8_0_0/design_1_decoder_3to8_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_decoder_3to8_0_0 || ORIG_REF_NAME==design_1_decoder_3to8_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_single_3_to_bus_0_0/design_1_single_3_to_bus_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_single_3_to_bus_0_0 || ORIG_REF_NAME==design_1_single_3_to_bus_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_bus_to_single_8_0_1/design_1_bus_to_single_8_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_bus_to_single_8_0_1 || ORIG_REF_NAME==design_1_bus_to_single_8_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_decoder_3to8_0_1/design_1_decoder_3to8_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_decoder_3to8_0_1 || ORIG_REF_NAME==design_1_decoder_3to8_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_single_3_to_bus_0_1/design_1_single_3_to_bus_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_single_3_to_bus_0_1 || ORIG_REF_NAME==design_1_single_3_to_bus_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_bus_to_single_8_0_2/design_1_bus_to_single_8_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_bus_to_single_8_0_2 || ORIG_REF_NAME==design_1_bus_to_single_8_0_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_decoder_3to8_0_2/design_1_decoder_3to8_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_decoder_3to8_0_2 || ORIG_REF_NAME==design_1_decoder_3to8_0_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_single_3_to_bus_0_2/design_1_single_3_to_bus_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_single_3_to_bus_0_2 || ORIG_REF_NAME==design_1_single_3_to_bus_0_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and_gate_0_0/design_1_and_gate_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and_gate_0_0 || ORIG_REF_NAME==design_1_and_gate_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and_gate_1_0/design_1_and_gate_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and_gate_1_0 || ORIG_REF_NAME==design_1_and_gate_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and_gate_2_0/design_1_and_gate_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and_gate_2_0 || ORIG_REF_NAME==design_1_and_gate_2_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_or_gate_0_0/design_1_or_gate_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_or_gate_0_0 || ORIG_REF_NAME==design_1_or_gate_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_or_gate_1_0/design_1_or_gate_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_or_gate_1_0 || ORIG_REF_NAME==design_1_or_gate_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and_gate_0_1/design_1_and_gate_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and_gate_0_1 || ORIG_REF_NAME==design_1_and_gate_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and_gate_1_1/design_1_and_gate_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and_gate_1_1 || ORIG_REF_NAME==design_1_and_gate_1_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and_gate_2_1/design_1_and_gate_2_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and_gate_2_1 || ORIG_REF_NAME==design_1_and_gate_2_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_or_gate_0_1/design_1_or_gate_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_or_gate_0_1 || ORIG_REF_NAME==design_1_or_gate_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_or_gate_1_1/design_1_or_gate_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_or_gate_1_1 || ORIG_REF_NAME==design_1_or_gate_1_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and_gate_0_2/design_1_and_gate_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and_gate_0_2 || ORIG_REF_NAME==design_1_and_gate_0_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and_gate_1_2/design_1_and_gate_1_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and_gate_1_2 || ORIG_REF_NAME==design_1_and_gate_1_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and_gate_2_2/design_1_and_gate_2_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and_gate_2_2 || ORIG_REF_NAME==design_1_and_gate_2_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_or_gate_0_2/design_1_or_gate_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_or_gate_0_2 || ORIG_REF_NAME==design_1_or_gate_0_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_or_gate_1_2/design_1_or_gate_1_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_or_gate_1_2 || ORIG_REF_NAME==design_1_or_gate_1_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and_gate_0_3/design_1_and_gate_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and_gate_0_3 || ORIG_REF_NAME==design_1_and_gate_0_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and_gate_1_3/design_1_and_gate_1_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and_gate_1_3 || ORIG_REF_NAME==design_1_and_gate_1_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and_gate_2_3/design_1_and_gate_2_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and_gate_2_3 || ORIG_REF_NAME==design_1_and_gate_2_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_or_gate_0_3/design_1_or_gate_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_or_gate_0_3 || ORIG_REF_NAME==design_1_or_gate_0_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_or_gate_1_3/design_1_or_gate_1_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_or_gate_1_3 || ORIG_REF_NAME==design_1_or_gate_1_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and_gate_0_4/design_1_and_gate_0_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and_gate_0_4 || ORIG_REF_NAME==design_1_and_gate_0_4} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and_gate_1_4/design_1_and_gate_1_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and_gate_1_4 || ORIG_REF_NAME==design_1_and_gate_1_4} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and_gate_2_4/design_1_and_gate_2_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and_gate_2_4 || ORIG_REF_NAME==design_1_and_gate_2_4} -quiet] -quiet

# IP: bd/design_1/ip/design_1_or_gate_0_4/design_1_or_gate_0_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_or_gate_0_4 || ORIG_REF_NAME==design_1_or_gate_0_4} -quiet] -quiet

# IP: bd/design_1/ip/design_1_or_gate_1_4/design_1_or_gate_1_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_or_gate_1_4 || ORIG_REF_NAME==design_1_or_gate_1_4} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and_gate_0_5/design_1_and_gate_0_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and_gate_0_5 || ORIG_REF_NAME==design_1_and_gate_0_5} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and_gate_1_5/design_1_and_gate_1_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and_gate_1_5 || ORIG_REF_NAME==design_1_and_gate_1_5} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and_gate_2_5/design_1_and_gate_2_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and_gate_2_5 || ORIG_REF_NAME==design_1_and_gate_2_5} -quiet] -quiet

# IP: bd/design_1/ip/design_1_or_gate_0_5/design_1_or_gate_0_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_or_gate_0_5 || ORIG_REF_NAME==design_1_or_gate_0_5} -quiet] -quiet

# IP: bd/design_1/ip/design_1_or_gate_1_5/design_1_or_gate_1_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_or_gate_1_5 || ORIG_REF_NAME==design_1_or_gate_1_5} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and_gate_0_6/design_1_and_gate_0_6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and_gate_0_6 || ORIG_REF_NAME==design_1_and_gate_0_6} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and_gate_1_6/design_1_and_gate_1_6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and_gate_1_6 || ORIG_REF_NAME==design_1_and_gate_1_6} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and_gate_2_6/design_1_and_gate_2_6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and_gate_2_6 || ORIG_REF_NAME==design_1_and_gate_2_6} -quiet] -quiet

# IP: bd/design_1/ip/design_1_or_gate_0_6/design_1_or_gate_0_6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_or_gate_0_6 || ORIG_REF_NAME==design_1_or_gate_0_6} -quiet] -quiet

# IP: bd/design_1/ip/design_1_or_gate_1_6/design_1_or_gate_1_6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_or_gate_1_6 || ORIG_REF_NAME==design_1_or_gate_1_6} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and_gate_0_7/design_1_and_gate_0_7.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and_gate_0_7 || ORIG_REF_NAME==design_1_and_gate_0_7} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and_gate_1_7/design_1_and_gate_1_7.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and_gate_1_7 || ORIG_REF_NAME==design_1_and_gate_1_7} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and_gate_2_7/design_1_and_gate_2_7.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and_gate_2_7 || ORIG_REF_NAME==design_1_and_gate_2_7} -quiet] -quiet

# IP: bd/design_1/ip/design_1_or_gate_0_7/design_1_or_gate_0_7.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_or_gate_0_7 || ORIG_REF_NAME==design_1_or_gate_0_7} -quiet] -quiet

# IP: bd/design_1/ip/design_1_or_gate_1_7/design_1_or_gate_1_7.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_or_gate_1_7 || ORIG_REF_NAME==design_1_or_gate_1_7} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and_gate_0_8/design_1_and_gate_0_8.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and_gate_0_8 || ORIG_REF_NAME==design_1_and_gate_0_8} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and_gate_1_8/design_1_and_gate_1_8.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and_gate_1_8 || ORIG_REF_NAME==design_1_and_gate_1_8} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and_gate_2_8/design_1_and_gate_2_8.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and_gate_2_8 || ORIG_REF_NAME==design_1_and_gate_2_8} -quiet] -quiet

# IP: bd/design_1/ip/design_1_or_gate_0_8/design_1_or_gate_0_8.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_or_gate_0_8 || ORIG_REF_NAME==design_1_or_gate_0_8} -quiet] -quiet

# IP: bd/design_1/ip/design_1_or_gate_1_8/design_1_or_gate_1_8.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_or_gate_1_8 || ORIG_REF_NAME==design_1_or_gate_1_8} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and_gate_0_10/design_1_and_gate_0_10.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and_gate_0_10 || ORIG_REF_NAME==design_1_and_gate_0_10} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and_gate_1_10/design_1_and_gate_1_10.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and_gate_1_10 || ORIG_REF_NAME==design_1_and_gate_1_10} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and_gate_2_10/design_1_and_gate_2_10.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and_gate_2_10 || ORIG_REF_NAME==design_1_and_gate_2_10} -quiet] -quiet

# IP: bd/design_1/ip/design_1_or_gate_0_10/design_1_or_gate_0_10.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_or_gate_0_10 || ORIG_REF_NAME==design_1_or_gate_0_10} -quiet] -quiet

# IP: bd/design_1/ip/design_1_or_gate_1_10/design_1_or_gate_1_10.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_or_gate_1_10 || ORIG_REF_NAME==design_1_or_gate_1_10} -quiet] -quiet

# IP: bd/design_1/ip/design_1_single_4_to_bus_0_1/design_1_single_4_to_bus_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_single_4_to_bus_0_1 || ORIG_REF_NAME==design_1_single_4_to_bus_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_bus_to_single_4_0_0/design_1_bus_to_single_4_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_bus_to_single_4_0_0 || ORIG_REF_NAME==design_1_bus_to_single_4_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_decoder_2to4_0_0/design_1_decoder_2to4_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_decoder_2to4_0_0 || ORIG_REF_NAME==design_1_decoder_2to4_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_single_2_to_bus_0_0/design_1_single_2_to_bus_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_single_2_to_bus_0_0 || ORIG_REF_NAME==design_1_single_2_to_bus_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_rom_1kx23_0_0/design_1_rom_1kx23_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_rom_1kx23_0_0 || ORIG_REF_NAME==design_1_rom_1kx23_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_single_23_to_bus_0_0/design_1_single_23_to_bus_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_single_23_to_bus_0_0 || ORIG_REF_NAME==design_1_single_23_to_bus_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_or_gate_0_11/design_1_or_gate_0_11.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_or_gate_0_11 || ORIG_REF_NAME==design_1_or_gate_0_11} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and_gate_0_12/design_1_and_gate_0_12.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and_gate_0_12 || ORIG_REF_NAME==design_1_and_gate_0_12} -quiet] -quiet

# IP: bd/design_1/ip/design_1_not_gate_1_1/design_1_not_gate_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_not_gate_1_1 || ORIG_REF_NAME==design_1_not_gate_1_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ram_0_0/design_1_ram_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_ram_0_0 || ORIG_REF_NAME==design_1_ram_0_0} -quiet] -quiet

# IP: ip/ram0/ram0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ram0 || ORIG_REF_NAME==ram0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_trans1_0_1/design_1_trans1_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_trans1_0_1 || ORIG_REF_NAME==design_1_trans1_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_not_gate_0_0/design_1_not_gate_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_not_gate_0_0 || ORIG_REF_NAME==design_1_not_gate_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_adpt_out_final_0_0_0/design_1_adpt_out_final_0_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_adpt_out_final_0_0_0 || ORIG_REF_NAME==design_1_adpt_out_final_0_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_adpt_out_12_0_0_0/design_1_adpt_out_12_0_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_adpt_out_12_0_0_0 || ORIG_REF_NAME==design_1_adpt_out_12_0_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_not_gate_2_0/design_1_not_gate_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_not_gate_2_0 || ORIG_REF_NAME==design_1_not_gate_2_0} -quiet] -quiet

# XDC: d:/coding/computer_organization/exp2nd/micro/project_1/project_1.gen/sources_1/bd/design_1/design_1_ooc.xdc
